[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-publishing-gradle-plugin = { id = "net.kyori.indra.publishing.gradle-plugin", version.ref = "indra" }
indra-licenser-spotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }

[versions]
jackson = "2.15.3"
paperweight = "1.5.9"
ktlint = "0.49.0"
indra = "3.1.3"

[libraries]
jacksonModuleKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
paperweightUserdev = { module = "io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweight" }

[bundles]
jackson = ["jacksonModuleKotlin"]
